version: "0.2"
language: en,es
dictionaryDefinitions: []
dictionaries: []
words:
  - cupertino
  - Otalora
  - riverpod
  - Scanline
  - Sebas
  - supabase
  - uuid
ignoreWords: []
import: []
enabledFileTypes:
  json: false
