version: "0.2"
language: en,es
dictionaryDefinitions: []
dictionaries: []
words:
  - cupertino
  - Otalora
  - pkce
  - recase
  - redimensiona
  - riverpod
  - scanline
  - Scanline
  - Sebas
  - supabase
  - uuid
  - webp
  - WEBP
ignoreWords: []
import: []
enabledFileTypes:
  json: false
