name: app_track_ota_labs
description: "A app to track my other develops"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.1.0
  nested: ^1.0.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/apps/

flutter_native_splash:
  color: "#0b1623"
  image: assets/splash.png
  branding: assets/branding.png
  image_dark: assets/splash.png
  branding_dark: assets/branding.png
  android_12:
    image: assets/splash.png
    color: "#0b1623"
    branding: assets/branding.png
    branding_dark: assets/branding.png
  ios: true
